name: todoapp

services:
  front-end:
    build:
      context: .
      dockerfile: ./FrontEnd/Dockerfile
    ports:
      - "8080:3000"

  project-management:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./ProjectManagement/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext
      - ConnectionStrings__MassTransitDbContext
      - JwtOptions__SecretKey

  integration-context:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./IntegrationContext/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext
      - ConnectionStrings__MassTransitDbContext
      - ClientUrl
      - JwtOptions__SecretKey

  auth-context:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./AuthContext/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext
      - JwtOptions__SecretKey

  api-gateway:
    depends_on:
      - project-management
      - integration-context
      - auth-context
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile

  rabbit-mq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
