name: todoapp

services:
  project-management:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./ProjectManagement/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext

  integration-context:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./IntegrationContext/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext

  auth-context:
    depends_on: 
      - rabbit-mq
    build:
      context: .
      dockerfile: ./AuthContext/Dockerfile
    environment:
      - ConnectionStrings__AppDbContext

  api-gateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    ports:
      - "8080:80"

  rabbit-mq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
